version: '3.9'
services:
  pgdb:
    image: postgres:16.2-alpine3.19
    container_name: pgdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 8888:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: